# Generated by Django 2.2.7 on 2019-11-07 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='google_data',
        ),
    ]
