# Generated by Django 2.2.7 on 2019-11-13 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20191107_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicuser',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topicuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='unituser',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='unituser',
            name='user',
        ),
        migrations.DeleteModel(
            name='SubjectUser',
        ),
        migrations.DeleteModel(
            name='TopicUser',
        ),
        migrations.DeleteModel(
            name='UnitUser',
        ),
    ]
