# Generated by Django 2.2.7 on 2019-11-14 05:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignments', '0003_assignment_semester'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubmitAssignments',
            new_name='SubmitAssignment',
        ),
    ]
