# Generated by Django 2.2.7 on 2019-11-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191113_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='7', max_length=200),
        ),
    ]
